#!/bin/bash
set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
OUT_FILE="${1:-$ROOT_DIR/ai/basic-memory/notes/_state-update-template.md}"

cd "$ROOT_DIR"

KEY_PATTERNS=(
  "README.md"
  "AGENTS.md"
  "Makefile"
  "main.tf"
  "cloud-init.yml"
  "deploy.sh"
  "PLAN.md"
  "TODO-security-hardening.md"
  "ansible/"
  "ai/"
)

CHANGED_FILES=()
while IFS= read -r line; do
  CHANGED_FILES+=("$line")
done < <(git diff --name-only HEAD)

RELEVANT_FILES=()
for file in "${CHANGED_FILES[@]}"; do
  for pattern in "${KEY_PATTERNS[@]}"; do
    if [[ "$file" == "$pattern" || "$file" == "$pattern"* ]]; then
      RELEVANT_FILES+=("$file")
      break
    fi
  done
done

mkdir -p "$(dirname "$OUT_FILE")"

{
  printf -- '---\n'
  printf 'title: State Update Template\n'
  printf 'permalink: state-update-template\n'
  printf 'tags:\n'
  printf -- '- openclaw\n'
  printf -- '- azure\n'
  printf -- '- template\n'
  printf -- '- memory\n'
  printf -- '---\n\n'
  printf '# State Update Template\n\n'
  printf 'Generated by `ai/skills/basic-memory-state-sync/run.sh`.\n\n'
  printf '## Candidate Observations\n\n'

  if [ "${#RELEVANT_FILES[@]}" -eq 0 ]; then
    printf -- '- [note] Keine relevanten Datei-Aenderungen erkannt; pruefe manuell auf kontextuelle Aenderungen.\n'
  else
    for f in "${RELEVANT_FILES[@]}"; do
      printf -- '- [change] Review `%s` und ueberfuehre belastbare Fakten in die passenden Memory-Notizen.\n' "$f"
    done
  fi

  printf '\n## Candidate Relations\n\n'
  printf -- '- relates_to [[OpenClaw Azure Setup - Current State]]\n'
  printf -- '- documented_in [[README]]\n'

  printf '\n## Notes\n\n'
  printf -- '- Nur verifizierte Fakten uebernehmen.\n'
  printf -- '- Keine Secrets oder Zugangsdaten dokumentieren.\n'
} > "$OUT_FILE"

printf 'Template written: %s\n' "$OUT_FILE"
